name: Publish from comments

on:
  issue_comment:
    types: [created]

jobs:
  publish:
    # https://github.com/cfug/dio/issues/1633
    if: github.event.issue.number == 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cfug/dio_issue_release_action@main
        with:
          github-token: ${{ secrets.PERSON_TOKEN }}
          pub-credentials-json: ${{ secrets.PUB_CREDENTIALS_JSON }}
          do-publish: false